hoverfly.host: localhost
hoverfly.admin.port: "8888"
hoverfly.proxy.port: "8500"
hoverfly.db.type: boltdb
hoverfly.username: "my_user"
hoverfly.password: "my_pass"
hoverfly.webserver: false
hoverfly.tls.certificate: ""
hoverfly.tls.key: ""
hoverfly.tls.disable: false