blank_issues_enabled: true
contact_links:
  - name: Questions about Hoverfly
    url: https://github.com/SpectoLabs/hoverfly/discussions/new?category=q-a
    about: Please ask questions and get support via GitHub Discussions
