sequenceDiagram
    participant Client application
    participant Hoverfly
    participant External service
    loop http
        Client application -->> External service: request
        External service -->> Client application: response
    end